export const popularStocks = [
  { symbol: 'AAPL', name: 'Apple' },
  { symbol: 'MSFT', name: 'Microsoft' },
  { symbol: 'GOOGL', name: 'Alphabet (Google)' },
  { symbol: 'AMZN', name: 'Amazon' },
  { symbol: 'TSLA', name: 'Tesla' },
  { symbol: 'META', name: 'Meta Platforms (Facebook)' },
  { symbol: 'NVDA', name: 'NVIDIA' },
  { symbol: 'JPM', name: 'JPMorgan Chase' },
  { symbol: 'V', name: 'Visa' },
  { symbol: 'MA', name: 'Mastercard' },
  { symbol: 'NFLX', name: 'Netflix' },
  { symbol: 'DIS', name: 'Disney' },
  { symbol: 'KO', name: 'Coca-Cola' },
  { symbol: 'PEP', name: 'PepsiCo' },
  { symbol: 'NKE', name: 'Nike' },
  { symbol: 'BA', name: 'Boeing' },
  { symbol: 'AMD', name: 'Advanced Micro Devices' },
  { symbol: 'INTC', name: 'Intel' },
  { symbol: 'ORCL', name: 'Oracle' },
  { symbol: 'IBM', name: 'IBM' },
  { symbol: 'WMT', name: 'Walmart' },
  { symbol: 'COST', name: 'Costco' },
  { symbol: 'BABA', name: 'Alibaba' },
  { symbol: 'TCS', name: 'Tata Consultancy Services (India – NSE: TCS)' },
  { symbol: 'INFY.NS', name: 'Infosys (India – NSE: INFY)' },
  {
    symbol: 'RELIANCE.NS',
    name: 'Reliance Industries (India – NSE: RELIANCE)',
  },
  {
    symbol: 'HDFCBANK.NS',
    name: 'HDFC Bank (India – NSE: HDFCBANK)',
  },
  {
    symbol: 'ICICIBANK.NS',
    name: 'ICICI Bank (India – NSE: ICICIBANK)',
  },
  { symbol: 'SBIN.NS', name: 'State Bank of India (India – NSE: SBIN)' },
  { symbol: 'ITC.NS', name: 'ITC Limited (India – NSE: ITC)' },
];
